services:
  redis:
    image: redis:latest
    container_name: redis-pp
    ports:
      - "6379:6379"
  flask:
    build: .
    container_name: flask
    ports:
      - "4000:4000"
    environment:
      REDIS_HOST: redis-pp  # Name of the Redis server container
      REDIS_PORT: 6379
    volumes:
      - .:/code
    depends_on:
      - redis
